phpcr_factories:
    jackalope.jackrabbit:
        class: '\Jackalope\RepositoryFactoryJackrabbit'
        parameters:
            - jackalope.jackrabbit_uri
            - credentials.username
            - credentials.password
        supportedOperations:
            - workspace.create
            - node.property.create
            - node.property.delete
            - node.property.update
            - node.delete
            - node.create
            - node.move
    jackalope.doctrine-dbal:
        class: '\Jackalope\RepositoryFactoryDoctrineDBAL'
        parameters:
            - jackalope.doctrine_dbal_connection
            - credentials.username
            - credentials.password
        supportedOperations:
            - workspace.create
            - workspace.delete
            - node.property.create
            - node.property.delete
            - node.property.update
            - node.delete
            - node.create
            - node.move
